### ISSUE TITLE
Existing file functionality doesn't seem to work

### ISSUE THREAD

**Issue by pceccato** [4np/grails-uploadr#37]
I'm using uploadr 1.1.1 and this example doesn't seem to work. Existing files are not displayed:

            <uploadr:add name="mySecondUploadr" path="${uploadPath}" direction="up" maxVisible="5" unsupported="${createLink(plugin: 'uploadr', controller: 'upload', action: 'warning')}">
                <g:each in="${files}" var="file">
                    <uploadr:file name="${file.name}">
                        <uploadr:fileSize>${file.size()}</uploadr:fileSize>
                        <uploadr:fileModified>${file.lastModified()}</uploadr:fileModified>
                        <uploadr:fileId>myId-${RandomStringUtils.random(32, true, true)}</uploadr:fileId>
                    </uploadr:file>
                </g:each>
            </uploadr:add>

**Comment by 4np** [comment]
Did you populate the ```files``` variable properly? S

**Comment by pceccato** [comment]
yes, I can render this on the same page.


    <g:each in="${files}" var="file">
      <p>
              ${file.name} ${file.size()} ${file.lastModified()} myId-${RandomStringUtils.random(32, true, true)} 
             <p>
              </g:each>

<uploadr:demo/> didn't seem to display them either...

**Comment by 4np** [comment]
Do you see any Javascript errors in the Javascript console?

**Comment by pceccato** [comment]
no. I'm using chrome as the browser.

**Comment by 4np** [comment]
It works just fine for me...

```
jeroen.wesbeek ~/Desktop $ git clone https://github.com/4np/grails-uploadr-demo.git
Cloning into 'grails-uploadr-demo'...
warning: templates not found /Users/jeroen.wesbeek/.git
remote: Counting objects: 166, done.
remote: Total 166 (delta 0), reused 0 (delta 0), pack-reused 166
Receiving objects: 100% (166/166), 458.56 KiB | 0 bytes/s, done.
Resolving deltas: 100% (52/52), done.
Checking connectivity... done.
jeroen.wesbeek ~/Desktop $ cd grails-uploadr-demo/
jeroen.wesbeek ~/Desktop/grails-uploadr-demo $ grails set-grails-version 
| Grails version updated to 2.4.4
jeroen.wesbeek ~/Desktop/grails-uploadr-demo $ grails run-app
| Compiling 10 source files

| Compiling 151 source files

| Running Grails application

| Server running. Browse to http://localhost:8080/grails-uploadr-demo
```

Uploading files using ```Example 2``` and reloading the page shows the local files as expected.

**Comment by pceccato** [comment]
thanks for you prompt response.

I will try cloning your demo project to troubleshoot my issue

**Comment by 4np** [comment]
No worries, let me know how it goes :)

**Comment by pceccato** [comment]
Thanks, I got it working. 

I was passing the upload path and the list of files to the view from the controller, like so:

        File uploadPath = new File("/uploads");
        def files = uploadPath.listFiles()
        render view: 'viewEdit', model: [ uploadPath:uploadPath, files:files ]

in my view, I verifed the the list of files by displaying them like so:

            <% files.each { file -> %>
            <p>${file.name} <p>
            <% } %>

However, this didn't work, no files were displayed.

            <uploadr:add name="uploader" path="${uploadPath}" direction="up" unsupported="${createLink(plugin: 'uploadr', controller: 'upload', action: 'warning')}">
            <% files.each { file -> %>
            <uploadr:file name="${file.name}">
                <uploadr:fileSize>${file.size()}</uploadr:fileSize>
                <uploadr:fileModified>${file.lastModified()}</uploadr:fileModified>
                <uploadr:fileId>myId-${RandomStringUtils.random(32, true, true)}</uploadr:fileId>
            </uploadr:file>
            <% } %>

But, this does work:

            <uploadr:add name="uploader2" path="${uploadPath}" direction="up" unsupported="${createLink(plugin: 'uploadr', controller: 'upload', action: 'warning')}">
                <% uploadPath.listFiles().each { f -> %>
                    <uploadr:file name="${f.name}">
                        <uploadr:fileSize>${f.size()}</uploadr:fileSize>
                        <uploadr:fileModified>${f.lastModified()}</uploadr:fileModified>
                        <uploadr:fileId>myId-${RandomStringUtils.random(32, true, true)}</uploadr:fileId>
                    </uploadr:file>
                <% } %>
            </uploadr:add>

which gave me a clue... so I changed the name of the variable that I passed to the view from files to fileList:

        File uploadPath = new File("/uploads");
        def files = uploadPath.listFiles()
        render view: 'viewEdit', model: [ uploadPath:uploadPath, fileList:files ]

And this worked perfectly:

            <uploadr:add name="uploader" path="${uploadPath}" direction="up" unsupported="${createLink(plugin: 'uploadr', controller: 'upload', action: 'warning')}">
            <% fileList.each { file -> %>
            <uploadr:file name="${file.name}">
                <uploadr:fileSize>${file.size()}</uploadr:fileSize>
                <uploadr:fileModified>${file.lastModified()}</uploadr:fileModified>
                <uploadr:fileId>myId-${RandomStringUtils.random(32, true, true)}</uploadr:fileId>
            </uploadr:file>
            <% } %>

Still don't know exactly why but thanks very much for pointingme in the right direction!

**Comment by 4np** [comment]
It's good to hear you got things working :+1:  I took a quick look at the Javascript initialization code, and it is actually using a ```file``` variable as well, probably overriding the ```file``` variable in your loop:

```
<g:each var="file" in="${files}" status="s">
```

I'll take a look at changing that variable to something less generic whenever I have some time to do some work on the plugin :) Thanks for reporting though!

**Comment by pceccato** [comment]
thanks for your help
