### ISSUE TITLE
Add ability to pass a url for the upload controller rather than controller and action

### ISSUE THREAD

**Issue by pceccato** [4np/grails-uploadr#38]
I just found out that the uploadr plugin breaks when I deployed my app to our corporate test environment, which is behind a TAM (Tivoli Access Manager) reverse proxy. TAM is required for authentication.

TAM does some magic rewriting the URLS and gets it wrong which causes my uploads to fail. this is because the javascript posts to:

myapp/upload/handle

which TAM rewites to:

https://tam.server.url/myapp/upload/handle

but it should really rewrite it to:

https://tam.server.url/magictext/myapp/upload/handle

is there any way for me to get the uploadr plugin to post to a url I supply such as:

https://tam.server.url/magictext/myapp/upload/handle

One way I can see to fix this is to hack your javascript and provide my own jquery.uploadr.js and uploadr.manifest.js, but I would rather not do this....

**Comment by pceccato** [comment]
I worked around this issue by making my own taglib which extended UploadrTagLib.

I added another tag <uploadr:addtam>, which takes an additional attribute called uri.

The body of this method is basically a cut and paste of the code in <uploadr;add>, except I override the uri with the one passed in via the uri attribute, if it exists.

If you are interested I could make a pull request with this change merged into the code for the <uploadr:add> tag so that it takes an additional parameter called uri which will contain the address of the web service which handles the upload.

**Comment by 4np** [comment]
It _should_ not be a problem as I have been running my [demo instance](http://uploadr.osx.eu/) behind both a reverse Apache proxy as well as a reverse Nginx proxy which do pretty much the same. It it probably due to the reverse proxy configuration in your ```TAM```. For example, take a look at the ```nginx``` configuration:

```
server {
	listen 80;
	server_name uploadr.osx.eu;

	access_log /var/log/nginx/osx.eu_uploadr.access_log main;
	error_log /var/log/nginx/osx.eu_uploadr.error_log info;

	location / {
		include conf.d/0_proxy;

		if ($uri !~ "^/uploadr-demo/") {
			rewrite ^/(.*)$ /uploadr-demo/$1 last;
		}

		proxy_pass http://192.168.2.10:8080;
	}
}
```

and the ```apache``` configuration that works as well:

```
<VirtualHost *:80>
	ServerName ci.uploadr.osx.eu

	ErrorLog /var/log/apache2/osx.eu_uploadr-ci-error.log
	CustomLog /var/log/apache2/osx.eu_uploadr-ci-access.log combined
	<IfModule mod_rewrite.c>
		RewriteEngine on

		# keep listening for the serveralias, but redirect to
		# servername instead to make sure only one user session
		# is created (tomcat will create one user session per
		# domain which may lead to two (or more) usersessions
		# depending on the number of serveraliases)
		# see uploadr ticket #321

		RewriteCond %{HTTP_HOST} ^ci.uploadr.osx.eu$ [NC]
		RewriteCond %{REQUEST_URI} ^/uploadr-demo/ [NC]
		RewriteRule ^/uploadr-demo/(.*)$ /$1 [L,PT,NC,NE]
	</IfModule>

	<IfModule mod_proxy.c>
		<Proxy *>
			Order deny,allow
			Allow from all
		</Proxy>

		ProxyStatus On
		ProxyPass / balancer://uploadr-cluster/uploadr-demo/ stickysession=JSESSIONID|jsessionid nofailover=On
		ProxyPassReverse / balancer://uploadr-cluster/uploadr-demo/
		ProxyPassReverseCookiePath /uploadr /

		<Location />
			SetOutputFilter proxy-html
		</Location>

		<Proxy balancer://uploadr-cluster>
			BalancerMember http://192.168.2.10:8080
		</Proxy>
	</IfModule>
</VirtualHost>
```

**Comment by pceccato** [comment]
yea I'm sure it's a tam configuration issue, unfortunately getting our tam
team to fix it is not gonna happen!

**Comment by 4np** [comment]
Long live corporate environments ;) If you want, please document your approach in this ticket so we have some documentation here for others that might run in your issue as well :)

**Comment by pceccato** [comment]
Hi, this is how I fixed my issue...

I found that TAM was causing network connection errors during file uploads, rather than try and get the corporate TAM team to fix it I decided to fix it myself by bypassing TAM for file uploads. 

1) I extendeded the uploadr taglib, adding a new tag called addtam which takes an additional parameter uri which overrides the uri that is created by the grails createLink code. You can see the codechanges in this commit: https://github.com/pceccato/grails-uploadr/commit/6990631ea72775a91e1e9d28826d4da07e0a6317

2) The uri I pass contains the machine name and port of my application, bypassing the TAM URL for file uploads.

        //
        // we are bypassing TAM so our upload is going directly to the host machine because TAM keeps giving us
        // netowrk connect errors
        //
        def portNumber = request.getServerPort()
        def serverName = request.getServerName()
        def nonTAMURL = "http://${serverName}:${portNumber}/strobe"

3) Since the uploader control is now uploading to a different domain name, it breaks cross site scripting protection in the browser , so I added the grails cors 1.1.6 plugin to allow cross site scripting.

4) had to configure cors to allow the headers used by the uploadr control as follows:

      cors.headers = [
        'Access-Control-Allow-Headers': 'origin, authorization, accept, content-type, 
                          cache-control, x-requested-with, 
                         x-file-name, x-file-size, x-uploadr-name'
       ]

5) since I am bypassing TAM I couldn't use its authentication, so I set my upload controller to be authenticated anonymously in spring security 'IS_AUTHENTICATED_ANONYMOUSLY', but this means spring security creates a new session, which breaks uploadr as it uses the session variable to pass the file save path.

6) had to implement my own upload controller which did not use the session variable to pass the upload file path.

**Comment by 4np** [comment]
Thanks a lot for documenting your fixes! :+1:
