### ISSUE TITLE
Pass a model the controller without specifying the path

### ISSUE THREAD

**Issue by GuillermoRivero** [4np/grails-uploadr#43]
Will be fine to allow the user to pass a model to the controller without specifying the path. In my project I want to send some extra arguments (model), but I don't need to specify the path.

```
// got a path attribute?
		if (attrs.get('path')) {
			// initialize session if necessary
			if (!session.uploadr) session.uploadr = [:]

			// and remember stuff in the session
			if (!session.uploadr[name]) {
				session.uploadr[name] = [
					uri		: uri,
					path	: attrs.path,
                    model   : model,
                    created : new Date()
				]
			} else if (session.uploadr[name].path != attrs.path) {
				// another uploadr with this name already exists in the session
                // spit out a warning
                log.error "uploadr: warning! Another uploadr with the same name (${name}) is already using another upload path (${attrs.path}). Make sure you are using unique names for your uploadr elements!"
			} else {
                // update the model in the session
                session.uploadr[name].model = model
                session.uploadr[name].lastUsed = new Date()
                session.uploadr[name].lastAction = "render"
            }
		}
```
Maybe creating session object with a null value on the path atribute or without path atribute can solve it, if you are agree I can make a pull request.

Greetings, and thanks for the pluging, such a nice work.

**Comment by 4np** [comment]
Hi Guillermo,

Thanks for the comments. Unfortunately I haven't been doing Grails for over 3 years and have shifted focus to fulltime iOS development. Therefore I have stopped maintaining the plugin. If you're interested in taking over, feel free to create a fork.

Cheers, Jeroen
